version: '3.8'

services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: incident_db
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d incident_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  alert-ingestion:
    build: ./services/alert-ingestion
    ports: ["8001:8001"]
    environment:
      - DB_URL=postgresql://user:password@database:5432/incident_db
    depends_on:
      database:
        condition: service_healthy
    # ðŸ’¡ On force la commande ici pour Ã©viter l'erreur d'argument
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    restart: always

  incident-management:
    build: ./services/incident-management
    ports: ["8002:8002"]
    environment:
      - DB_URL=postgresql://user:password@database:5432/incident_db
    depends_on:
      database:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    restart: always

  oncall-service:
    build: ./services/oncall-service
    ports: ["8003:8003"]
    environment:
      - DB_URL=postgresql://user:password@database:5432/incident_db
    depends_on:
      database:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8003
    restart: always

  web-ui:
    build: ./services/web-ui
    ports: ["8080:80"] # VÃ©rifie si c'est 80 ou 8080 dans ton Dockerfile
    depends_on:
      - incident-management

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports: ["9090:9090"]
    restart: always

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports: ["3000:3000"]
    depends_on:
      - prometheus
    restart: always

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
