global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'incident_services'
    static_configs:
      - targets: ['alerts-api:3000', 'incidents-api:3000', 'oncall-api:3000', 'web-ui:3000']