global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'incident_platform'
    static_configs:
      - targets: 
        - 'alert-ingestion:8001'
        - 'incident-management:8002'
        - 'oncall-service:8003'